In [4]:
import tensorflow as tf
import numpy as np

In [19]:
# Example input data with sequences of length 3
input_data = np.array([[1, 2, 3, 4]])

# Define the embedding layer
embedding_size = 4
vocab_size = 10
embedding_layer = tf.keras.layers.Embedding(input_dim=vocab_size, output_dim=embedding_size, input_length=3)

# Apply the embedding layer to the input data
embedded_data = embedding_layer(input_data)

# Print the original and embedded data
print("Original Input Data:")
print(input_data)

print("\nEmbedded Data:")
print(embedded_data.numpy())
print(embedded_data.numpy().shape)


Original Input Data:
[[1 2 3 4]]

Embedded Data:
[[[-0.0149781  -0.02442976  0.02281013  0.00162014]
  [ 0.01873421 -0.01610229 -0.03243386  0.04829535]
  [ 0.03758735  0.03599087 -0.01888402 -0.01882864]
  [-0.03374155  0.03429857 -0.03001671 -0.03581722]]]
(1, 4, 4)


In [17]:
embedding_layer.weights

[<tf.Variable 'embedding_6/embeddings:0' shape=(10, 4) dtype=float32, numpy=
 array([[ 0.03605654,  0.04244219, -0.04763841, -0.01573974],
        [ 0.00870035,  0.01802123, -0.00633644,  0.04599639],
        [-0.01107519,  0.03048099, -0.04809731,  0.03882614],
        [-0.00512581, -0.0016821 ,  0.0127919 ,  0.02775532],
        [-0.0099294 , -0.03650414,  0.03527318,  0.04310865],
        [ 0.04217825,  0.01715516,  0.00508072, -0.04289785],
        [ 0.03938809, -0.03958308, -0.00490121, -0.04891822],
        [ 0.04659427, -0.02871102,  0.01538889, -0.0493192 ],
        [-0.04023143, -0.00989513,  0.00542838, -0.01371833],
        [ 0.02628987, -0.03822715,  0.04243076, -0.01340281]],
       dtype=float32)>]